- name: Install minimal packages
  ansible.builtin.package:
    name:
      - curl
      - util-linux-systemd
      - grep
      - awk
      - util-linux
      - open-iscsi
      - nfs-client
      - w3m
      - wget
      - telnet
      - timezone 
      - less 
      - vim 
      - iproute2 
      - iputils 
      - bind-utils 
      - wireshark 
      - tcpdump 
      - traceroute 
#      - s3cmd 
      - lynx
      - git
    state: latest
  
- name: Copy the scripts to usr_local_bin
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: root
    mode: 0755
  loop:
    - "etcd"
    - "etcdctl"
    - "etcdutl"
    - "helm"