- name: Install minimal packages
  ansible.builtin.package:
    name:
      - curl
      - util-linux-systemd
      - grep
      - awk
      - util-linux
      - open-iscsi
      - nfs-client
    state: latest
  
- name: Start service iscsid, if not started
  ansible.builtin.service:
    name: iscsid
    state: started